name: deployment

on:
  push:
    branches: [master]

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_DEPLOY }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com

      # erase everything below this comment if you do not wish to generate a pdf for the OER
      # If you want to generate a pdf, alter lines 55 and 58.

      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Install Prince
        run: |
          curl -L -o prince.tar.gz https://www.princexml.com/download/prince-15.2-linux-generic-x86_64.tar.gz
          tar -xzf prince.tar.gz
          sudo ./prince-*/install.sh

      - name: Build PDF
        run: npx docusaurus-prince-pdf -u https://patrick-crawford.github.io/WebProgrammingForAppsAndServices/ -o ./pdf/WebProgrammingForAppsAndServices.pdf

      - name: Push PDF to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_DEPLOY }}
          publish_dir: ./pdf
          publish_branch: gh-pages
          destination_dir: pdf
          commit_message: 'Add generated PDF'
